---
- hosts: linux
  become: true
  tasks:
  - name: Setup repository
    yum_repository:
      name: logstash-7.x
      description: Elastic repository for 7.x packages
      baseurl: https://artifacts.elastic.co/packages/7.x/yum
      gpgcheck: yes
      metadata_expire_filter: read-only:future
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - package:
      name:
      - logstash
      - epel-release
      - filebeat
      - elasticsearch
      - kibana
      - tmux
      - java-11-openjdk-headless
      state: present

  - name: Copy ca
    copy:
      src: "ca-cert.pem"
      dest: "/etc/logstash/ca-cert.pem"

  - name: Copy cert
    copy:
      src: "logstash-cert.pem"
      dest: "/etc/logstash/logstash-cert.pem"

  - name: Copy key
    copy:
      src: "logstash-key.pem"
      dest: "/etc/logstash/logstash-key.pem"

  - name: Create pipeline
    become: true
    copy:
      dest: /etc/logstash/conf.d/local-logstash.conf
      content: |
        input {
          beats {
            port => "5044"
            ssl => true
            ssl_certificate_authorities => ["/etc/logstash/ca-cert.pem"]
            ssl_certificate => "/etc/logstash/logstash-cert.pem"
            ssl_key => "/etc/logstash/logstash-key.pem"
            ssl_verify_mode => "force_peer"
          }
        }
        filter {
          geoip {
            source => "clientip"
          }
        }
        output {
          file { path => "/home/vagrant/output" }
          elasticsearch {
            hosts => [ "localhost:9200" ]
          }
        }

  - name: start elasticsearch
    become: true
    systemd:
      name: "{{ item }}"
      state: started
    loop:
    - elasticsearch
    - kibana

  - name: Start logstash
    shell: 'tmux new-session -d -s logstash "/usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/local-logstash.conf --config.reload.automatic"'
    ignore_errors: true

  - name: Create motd
    become: true
    copy:
      dest: /etc/motd
      content: |
        http://localhost:5601/app/kibana


- hosts: windows
  tasks:

    # https://docs.ansible.com/ansible/2.7/modules/win_package_module.html#win-package-module
    # HKLM:Software\Microsoft\Windows\CurrentVersion\Uninstall
    - name: install winlogbeat
      win_package:
        path: https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-7.6.0-windows-x86_64.msi
        state: present
        product_id: '{2DE7C165-4793-5EE1-9DF0-372062953E2B}'

    - name: ca-cert copy
      win_copy:
        dest: 'c:/programdata/Elastic/Beats/winlogbeat/ca-cert.pem'
        src: "ca-cert.pem"

    - name: clientcert
      win_copy:
        dest: 'c:/programdata/Elastic/Beats/winlogbeat/winlogbeat-cert.pem'
        src: "winlogbeat-cert.pem"

    - name: clientkey
      win_copy:
        dest: 'c:/programdata/Elastic/Beats/winlogbeat/winlogbeat-key.pem'
        src: "winlogbeat-key.pem"

    - name: Add hostname (centos-01)
      win_hosts:
        state: present
        canonical_name: "centos-01"
        ip_address: "{{ hostvars['linux']['ansible_default_ipv4']['address'] }}"

    - name: Add hostname
      win_hosts:
        state: present
        canonical_name: "{{ hostvars['linux']['ansible_hostname'] }}"
        ip_address: "{{ hostvars['linux']['ansible_default_ipv4']['address'] }}"

    # https://stackoverflow.com/questions/32025776/how-to-get-ip-address-from-other-host-in-ansible
    - name: Configuratie bouwen
      win_copy:
        dest: '%ProgramData%\Elastic\Beats\winlogbeat\winlogbeat.yml'
        content: |
          winlogbeat.event_logs:
            - name: Application
            - name: Security
            - name: System

          output.logstash:
            hosts: [{{ hostvars["linux"]["ansible_hostname"] }}:5044]
            ssl.certificate_authorities: ["c:/ProgramData/Elastic/Beats/winlogbeat/ca-cert.pem"]
            ssl.certificate: "c:/ProgramData/Elastic/Beats/winlogbeat/winlogbeat-cert.pem"
            ssl.key: "c:/ProgramData/Elastic/Beats/winlogbeat/winlogbeat-key.pem"
            ssl.verification_mode: full

          logging.to_files: true
          logging.files:
            path: C:\ProgramData\Elastic\Logs
            logging.level: info

    - name: restart Winlogbeat
      win_service:
        name: winlogbeat
        state: restarted
      ignore_errors: true
