#!/bin/bash

ansible-playbook --check playbook.yml || exit
ansible-playbook --syntax-check playbook.yml || exit
ansible-lint playbook.yml

rm *.retry
> log

vagrant destroy -f
for vm in $(sudo virsh list --all --name); do
	sudo virsh destroy $vm;
	sudo virsh undefine $vm;
done
vagrant destroy -f

rm -rf .vagrant

vagrant up $*
vagrant ssh-config > ~/.ssh/vagrant
#ssh linux

# nu met forwarded porten
#vagrant ssh linux -- -L 5601:localhost:5601
